services:
  open-surplus-manager:
    container_name: open-surplus-manager
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    environment:
      CONFIG_FILE: /config/config.yaml
    volumes:
      - ../config.yaml:/config/config.yaml
    ports:
      - 8080:8080